language: generic
sudo: required

before_install:
  - docker build -t nancibonfim/docker-k8s -f Dockerfile.dev .

script:
  - docker run -e CI=true nancibonfim/docker-k8s npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "iRvIb7LxLmWmVfNDbDSpj3TG1nt65plz6fsDnfwvfWtCJz5IhdPh6LX9J/98vQ56x5HcSW7AOZJrjLWvlAA4H+t2LPjb9IY9dmFLmmjsMN1U3jtP4yXbkEkaPSoTUZXOzJQqrHLtyHWwxaZDKrIfzQOdT+UDj8SJu2EnTMmx+KnUH5j/GkkKhUyYRALpkJ/np7YwgCIWPFCvAs7TujUCbLaGiKyhdgINu3dqo/HGJq3BG3fYg6lsZIRkqA4gCRvHayvRhhdEg8WSsFYDQD+Z89lvpWrRW8YObUgeEUHiAIZUO0sAJdTn+H7CUWH1QpgS2TBpMQTn2shrMTKea+sH9cZSQOBkdh/Bw4xFeBTbaW0EMuMjhG1YZD+rElUfFrMysNfUS1oXqBWn007UFv1rTNMiQ2FDrkqyhdiAv2Crw+ztYnffxACo1B9wYXrFExYWOrl+SXXJkf7+SmMouWWnJAxUvwHmflshdiR/3duHCwILQ3dvSDQeKf2+cQxhXp/nE3ADIOKttkN1XrLZjy+eaw8ZXZ8il1GVBF2rAAe3pLW3+mqpBoE0VOie982zBC3I2NRXGpOVEATRGnvoJvwngFhIYdMyhH9i0EuvqjwjwDPcdo1+UTfp9oZde/K6LznWAh6UILAkGWuNc3q5VziPZMA/IXvH+RuEug8VDYudJrs="
  secrect_access_key:
    secure: "ZqJd39y+hVRj2TOpQXH3Jh2evLh1zAtq1NBUx7YrZn9ZNyp99xvQum2092ucLYxcHxyPoBXauDJUG80bdFl2cvP2s2xNDB+VxMBuj0tvfLnZpC+bX8d2nRtYqLZ+xuz0mJPjlQmERWHQZb7D4dbBtW+ba1PrrPlEW2/1u0Uo0EfpdQkmVkTq1XZeG4HXvAqHSRWTWe5O4RyHBLQZ8l0m4T0T2+Gix8Z/zmnHEat1lx4OtZNUWhJl2OWgr2kAXZIbHqWkPa2xeBceNy+J7v1rAXD5ZZhTH1NqtTGOACIW1/Hb6RdHJWuHr+bjleoIlATqX+FFFvcyM4ilekZX7K5WBbT09qQ0dejkgrNLpBEThBo/Z1OowO1KAy50ANekdTeRmUj6G1WfX8NnlBzJJ9svNFs7H6j6reoZQHGPtszChEXxnFlZWmplDr3JUTZ9+iHStFLEMWwwW76s23DFm0ntHgVEdqAOJdnJWIBsuzUHjfD/BCWVLEGYzm8PD5fZBM2RTKk42bwME/QEVw9VEheSCzYpLWUDUHwPoPTjEyCxT0mIQQr0JiuEBM0XCXsIwZAJ+wq2EwiSUjhAHrKlcdnFhKH4Nz0wbF44ZGE2jFlNTlieEamFP+nIGY+vtazcZqRU22M4tAGQPLPKTGVqtIEX/7zkTb7Ctk21i0iKFpiM6Ks="
  region: "sa-east-1"
  app: "docker-react"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-sa-east-1-885646535386"
  bucket_path: "docker-react"
  true:
    branch: main
env:
  global:
    secure: "Jv8bSq+yHMFtyXUJe4pgZx6dno23iUzo5gQsZX12mIk+RJ4MKkcO2Fs3jPegRvaT7V5eHe9mOLXf5zHkhy+5naetaJUyV0Pgmvm08IM/3N1n5WtRsPdnGYjdt3S8IPZw63v6CBafSxSPDzAgE4siSGtYqwsaznCbiDmWHCv4J8mzY3mIzWfzyYdqXezDqjSMLxMSaKAHFeUepvS+rSLtW2Rszoh/R2rKM12FTE6Kc55v1JreQs6oWrgSOIpxbblD2XkYWDmLCuxhI10GVOuCzd5v4J7jnLSVJ+OEIVVuIja+/tWRFDm0sH1u0KBvMo/qzOc8cntkKcpwQODQqqLH7dTTxPgRaBEazJ7igh1BB/lCqyBimPu6esRf23NtfC35bDwmPdVhdgUaRspnWPob6fFTyP4EpE7lUo3E7JRJ2m0MkR5X6TsjIvbdGo4GPHonIsKUkKl4q7TAefQvRbsWDtJnq6HpAbt6OEjY6vXKFFxvFtzXgTvNCk+klDUutUs+3H1r+dkl95y82Nax9MKciqpaB2uabL1apYaOAkf8YuUdPPD7gzWYuCGEbRAayzE6zstibX+26XKT4x4PX5njJ2Ea3hM0Ky/3ahveXNXKDyEzP+vV8l9Zbl1yu3OPXM1lbsgqWTa/YTtHfYWEfO5SO2g5I6sKotRf1ULj0cgyRlU="
